"""Initial migration

Revision ID: 89086b32355f
Revises: 
Create Date: 2025-12-03 21:47:20.685118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89086b32355f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('government_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('government_info')
    # ### end Alembic commands ###
